version = 0.1
[default.deploy.parameters]
stack_name = "sam-hiberry-clients"
resolve_s3 = true
s3_prefix = "sam-hiberry-clients"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"development\" LogLevel=\"INFO\""
image_repositories = []
