AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-hiberry-app-orders

Globals:
  Function:
    Timeout: 120

Parameters:
  ShopifyEventBusName:
    Type: String
  StageName:
    Type: String
    Default: development
    AllowedValues:
      - local
      - development
      - uat
      - prod
Resources:

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: delivery_date
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: delivery_date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HiBerryLocationIndex:
    Type: AWS::Location::PlaceIndex
    Properties:
      DataSource: Esri
      Description: Place index for locating delivery address Using Esri
      IndexName: HiBerrySearchIndex
      PricingPlan: RequestBasedUsage

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreateOrderFunction-${StageName}"
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: create-order
          POWERTOOLS_LOG_LEVEL: INFO
          APP_ENVIRONMENT: !Ref StageName
      Events:
        HttpPost:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /order
            Method: post
      Role: !GetAtt CreateOrderRole.Arn

  ShopifyOrderIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ShopifyOrderIntegrationFunction-${StageName}"
      CodeUri: integration/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          CREATE_ORDER_FUNCTION_NAME: !Ref CreateOrderFunction
          POWERTOOLS_SERVICE_NAME: shopify-order-integration
          POWERTOOLS_LOG_LEVEL: INFO
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt ShopifyOrderIntegrationDLQ.Arn
      Events:
        ShopifyOrder:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref ShopifyEventBusName
            Pattern:
              detail-type:
                - "shopifyWebhook"
              detail:
                metadata:
                  X-Shopify-Topic:
                    - prefix: "orders/create"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateOrderFunction

  ShopifyOrderIntegrationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ShopifyOrderIntegrationDLQ

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CreateOrderFunction.Arn
      Principal: apigateway.amazonaws.com

  CreateOrderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "CreateOrderRole-${StageName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBPutItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt OrdersTable.Arn

  LambdaInvokeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CreateOrderInvokeRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaInvokePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: !GetAtt CreateOrderFunction.Arn

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      # Auth:
      #   DefaultAuthorizer: MyCognitoAuthorizer
      #   Authorizers:
      #       MyCognitoAuthorizer:
      #         UserPoolArn:
      #           Fn::GetAtt:
      #             - HiBerryUserPool
      #             - Arn

  # HiBerryCognitoAuthorizer:
  #   Type: AWS::ApiGateway::Authorizer
  #   Properties:
  #     Name: HiBerryCognitoAuthorizer
  #     Type: COGNITO_USER_POOLS
  #     IdentitySource: method.request.header.Authorization
  #     RestApiId: !Ref ApiGateway
  #     ProviderARNs:
  #       - !GetAtt HiBerryUserPool.Arn


Outputs:
  CreateOrderFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  HttpApiEndpoint:
    Description: The default endpoint ApiGateway.
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"