name: orders_pipeline

on:
  push:
    paths:
      - 'src/orders/**'
    branches:
      - 'main'
      - 'feature**'
  workflow_dispatch:
jobs:
  run_unit_tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install dependencies
        run: |
          make install
        working-directory: ./tests
      - name: Run tests
        run: |
          make test
        working-directory: ./tests

  development: 
    env:
      STAGE_NAME: development
    environment: {{ env.STAGE_NAME }}
    if: startsWith(github.event.ref, 'refs/heads/main')
    uses: ./.github/workflows/pipeline_template.yaml
    needs: [run_unit_tests]
    with: 
      stack_name: ${{ vars.ORDERS_STACK_NAME }}
      sam_deploy_overrides: "ShopifyEventBusName=${{ vars.SHOPIFY_EVENT_BUS_NAME }} StageName={{ env.STAGE_NAME }}"
      sam_template: src/orders/template.yaml
      aws_region: us-east-1
      pipeline_execution_role: {{ vars.PIPELINE_EXECUTION_ROLE }}
      cloudformation_execution_role: {{ vars.CLOUDFORMATION_EXECUTION_ROLE }}
      artifacts_bucket: {{ vars.ARTIFACTS_BUCKET }}
      stage_name: {{ env.STAGE_NAME }}
    secrets: 
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_MBU }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MBU }}

#TODO- Discuss UAT and PROD