AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-hiberry-app-products

Globals:
  Function:
    Timeout: 120
  Api:
    Cors:
        AllowHeaders: "'Content-Type,Authorization,authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'3600'"
        AllowMethods: "'HEAD,OPTIONS,POST,GET,PUT,DELETE'"
        AllowCredentials: "'false'"
    GatewayResponses:
        DEFAULT_4xx:
            ResponseParameters:
                Headers:
                    Access-Control-Allow-Headers: "'Content-Type,Authorization,authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                    Access-Control-Allow-Origin: "'*'"
                    Access-Control-Allow-Methods: "'HEAD,OPTIONS,POST,GET,PUT,DELETE'"
        DEFAULT_5xx:
            ResponseParameters:
                Headers:
                    Access-Control-Allow-Headers: "'Content-Type,Authorization,authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                    Access-Control-Allow-Origin: "'*'"
                    Access-Control-Allow-Methods: "'HEAD,OPTIONS,POST,GET,PUT,DELETE'"

Parameters:
  StageName:
    Type: String
    Default: development
    AllowedValues:
      - local
      - development
      - uat
      - prod
  #TODO Add POWERTOOLS_LOG_LEVEL
Resources:

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Products
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreateProductFunction-${StageName}"
      CodeUri: .
      Handler: lambda_function.create_product
      Runtime: python3.11
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: create-product
          POWERTOOLS_LOG_LEVEL: DEBUG
          APP_ENVIRONMENT: !Ref StageName
      Events:
        HttpPost:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products
            Method: post
            Auth:
              Authorizer: HiBerryCognitoAuthorizer
      Role: !GetAtt CreateProductRole.Arn

  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetAllProductsFunction-${StageName}"
      CodeUri: .
      Handler: lambda_function.get_all_products
      Runtime: python3.11
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: get-all-products
          POWERTOOLS_LOG_LEVEL: DEBUG
          APP_ENVIRONMENT: !Ref StageName
      Events:
        HttpPost:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products
            Method: get
            Auth:
              Authorizer: HiBerryCognitoAuthorizer
      Role: !GetAtt GetAllProductsRole.Arn

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "DeleteProductFunction-${StageName}"
      CodeUri: .
      Handler: lambda_function.delete_product
      Runtime: python3.11
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: delete-product
          POWERTOOLS_LOG_LEVEL: DEBUG
          APP_ENVIRONMENT: !Ref StageName
      Events:
        HttpDelete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products
            Method: delete
            Auth:
              Authorizer: HiBerryCognitoAuthorizer
      Role: !GetAtt DeleteProductRole.Arn

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "UpdateProductFunction-${StageName}"
      CodeUri: .
      Handler: lambda_function.update_product
      Runtime: python3.11
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: update-product
          POWERTOOLS_LOG_LEVEL: DEBUG
          APP_ENVIRONMENT: !Ref StageName
      Events:
        HttpPut:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products
            Method: put
            Auth:
              Authorizer: HiBerryCognitoAuthorizer
      Role: !GetAtt UpdateProductRole.Arn

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        Authorizers:
          HiBerryCognitoAuthorizer:
            UserPoolArn:
              - !Sub 
                - 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'
                - UserPoolId: !ImportValue HiBerryUserPoolIdExport

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CreateProductFunction.Arn
      Principal: apigateway.amazonaws.com

  CreateProductRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "CreateProductRole-${StageName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBPutItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt ProductsTable.Arn
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  GetAllProductsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "GetAllProductsRole-${StageName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: QueryDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource: !GetAtt ProductsTable.Arn
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
                                
  UpdateProductRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "UpdateProductRole-${StageName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UpdateDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt ProductsTable.Arn
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  DeleteProductRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "DeleteProductRole-${StageName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBDeleteItemPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                Resource: !GetAtt ProductsTable.Arn
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
Outputs:
  CreateProductFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt CreateProductFunction.Arn
  HttpApiEndpoint:
    Description: The default endpoint ApiGateway.
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
